version: '3'
services:
  flask:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: flask
    restart: unless-stopped
    environment:
      APP_DEBUG: "True"
      APP_PORT: 5000
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: rootpassword
      MONGODB_HOSTNAME: mongodb_container
    ports:
      - 5000:5000
    depends_on:
      - mongodb_container
    networks:
      - backend
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - backend

volumes:
  mongodb_data_container:
networks:
  backend:
    driver: bridge
